### ISSUE TITLE
Media with an apostrophe ' in the title are inadvertently removed.

### ISSUE THREAD

**Issue by mhoskinson7** [arlinsandbulte/Pro7-Media-Sweeper#10]
I have 2 media files with an apostrophe ' in the titles that are located in presentations and media bins. They are removed even though they are in use. I'm guessing the apostrophe ' is the culprit.

[Sweep_Log (20220120-093629).log](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/7906513/Sweep_Log.20220120-093629.log)

Their titles are:
**Heaven's Helper.png**
**Mother's RoomFamily Room.png**

**Comment by arlinsandbulte** [comment]
Yep, the apostrophe ' is certainly the culprit.
I'll see what I can do.  Thanks for the report.

sigh: 
Dates/Times & character encoding are two of the hardest things in computer programing.
Thankfully, I'm not dealing with Dates/Times much in here.
Languages / character encoding on the other hand .... :-(

**Comment by mhoskinson7** [comment]
For now, I'll adjust our graphics from our designer to remove apostrophes. Thanks for putting time into this as it definitely cleans the ProPresenter folder up in less time than searching through it all!

**Comment by arlinsandbulte** [comment]
I think I have found a solution for this.  I'll flush it out, test it some more and hopefully post it later tonight.

**Comment by arlinsandbulte** [comment]
Version v2.0.0-RC5 is released and should solve this issue.
Thanks!
