### ISSUE TITLE
Don't remove audio files that are in audio playlists

### ISSUE THREAD

**Issue by dali01** [arlinsandbulte/Pro7-Media-Sweeper#11]
Audio files that are part of an audio playlist seem to be removed by this tool. Shouldn't they be excluded?

**Comment by arlinsandbulte** [comment]
No, it should not remove audio files included in an audio playlist.
I just checked, and the audio files in my audio playlists are not removed.

What platform are you using, Mac or Win?
What version of ProPresenter are you using?

**Comment by dali01** [comment]
I must admit that it's been a few weeks since I tried it in our production environment (Win 10, ProP 7.6.1). I'm gonna give it another try this coming weekend (but on ProP 7.8.3) and report back.

**Comment by arlinsandbulte** [comment]
OK.  Please let me know what you find out.
Pro7 Media Sweeper should work with just about any version of Pro7.  
I did most of the development and testing on Pro7.7.1 in Windows.
I have not found any issues with it on any of the 7.8 versions.

Also, if you continue to see issues, please attach the log file.
Thanks!

**Comment by arlinsandbulte** [comment]
@dali01 Have you been able to recreate or confirm the problem you found with audio playlists here?
Thanks.

**Comment by arlinsandbulte** [comment]
No response confirming the original issue.
And I have not been able to recreate the issue.

**Comment by dali01** [comment]
Sorry for the lack of response. I haven't been able to verify yet. If I still have the issue, I'll let you know.

**Comment by dali01** [comment]
@arlinsandbulte Late follow up; The removed files were duplicates, the audio files that were in a playlist did not get removed.
All good, it was just a misunderstanding.

**Comment by arlinsandbulte** [comment]
Great news!
Thanks for the follow up!
