### ISSUE TITLE
v2.2 - Parse Error With Every Run

### ISSUE THREAD

**Issue by Brotuulaan** [arlinsandbulte/Pro7-Media-Sweeper#12]
I'm getting an error that might be due to a Pro7 update since you last reworked how your utility checks files (?).

ERROR: DecodeError("Error parsing message with type 'rv.data.PlaylistDocument'") occurred trying to parse C:\Users\Rise Streaming PC\Documents\ProPresenter\Playlists\Templates\PlaylistTemplates

Does this mean I have a corrupt file? I haven't seen anything that would indicate so in my Pro7 logs, and I've been up and down them like no one's business the past three months trying to chase down massive log growth due to an error even many of the CS gents don't recognize. If the file is having issues, I'll want to submit that to them for analysis.

**Comment by arlinsandbulte** [comment]
What version of Pro7 are you seeing this on?
Are you using Windows or Mac?
Also, is that Error message from the Pro7 Media Sweeper log file?  Or does it cause Pro7 Media Sweeper to crash?

**Comment by Brotuulaan** [comment]
We're running 7.10.4, Windows. It's from the log, and the sweeper finishes the process just fine as far as I can tell—no crashes. It gives me that popup every time and tells me to search the log for the error.

**Comment by arlinsandbulte** [comment]
OK.  Thanks.
Looking at this again, this might be due to a new feature.
Playlist templates is a pretty new feature that did not exist when I made this utility.
I bet there is no issue.  I just need to account for that new feature.

I probably have not seen this because I’ve never used a Playlist Template.  So, my install does not even have that file: “\ProPresenter\Playlists\Templates\PlaylistTemplates”
Do you use Playlist Templates?

**Comment by arlinsandbulte** [comment]
@greyshirtguy updated the [proto library](https://github.com/greyshirtguy/ProPresenter7-Proto) that is used in this project.  I'll look at updating that here.

HOWEVER:
I tested v2.2.0 after I added a Playlist Template and did not get any parse errors.
So, maybe there is more going on here than just keeping pace with ProPresenter updates.  I can't rule out a corrupt file yet....

**Comment by greyshirtguy** [comment]
It's interesting that you did not get any errors after generating a new \ProPresenter\Playlists\Templates\PlaylistTemplates file.

The error  
    
 `ERROR: DecodeError("Error parsing message with type 'rv.data.PlaylistDocument'") occurred trying to parse C:\Users\Rise Streaming PC\Documents\ProPresenter\Playlists\Templates\PlaylistTemplates`  
  
suggests an attempt to decode the file `PlaylistTemplates` as an `rv.data.PlaylistDocument` (as defined in `propresenter.proto`)

Treating it as a `PlaylistDocument` should/will fail.  The exact error is uninmportant and may vary - but it's not a `PlaylistDocument` and should not decode as one.  

![image](https://user-images.githubusercontent.com/1886513/214712926-c75669f5-9d83-4b06-b759-8ba1c718ae2d.png)

 Instead, it should be decoded as a `PlaylistTemplate` (as defined in `playlistTemplate.proto`)
 That will work.  eg:
 
![image](https://user-images.githubusercontent.com/1886513/214713508-830f73e0-985c-418c-8e8a-fd90c8427817.png)

**Comment by Brotuulaan** [comment]
I've recently started using them, yes. I don't recall whether I saw this error every single time I've run it and discounted/ignored it since it did the job correctly the first several times or if it's only recently started since I've only used it a handful of times. I think my first time using it was within a few months of my first time creating a template. Is there a way to submit my template file so you can drop it into your instance and run some tests? I tried dropping it in here, but it doesn't support the filetype.

**Comment by Brotuulaan** [comment]
Oh, the page refreshed after I submitted that comment and now shows greyshirtguy's comment. Should I take this to mean the error is to be expected given current code, and I don't need to submit my file for testing?

**Comment by greyshirtguy** [comment]
By all means, please attach that file - It's a good idea to quickly check it decodes without error - to eliminate the possibilitiy of corrupt file.  IMHO I suspect it will be fine... but I'm curious too and will quickly decode it to check it and eliminate that option.... (and I bet Arlin feels the same)

**Comment by arlinsandbulte** [comment]
@Brotuulaan Yes.  Please attach the file here so I can test it out myself.
If you put in in a zip archive first, it should allow you to upload it here.
Thanks!

**Comment by Brotuulaan** [comment]
Oh, duh. I didn't even consider that the filetype can technically be "changed" by means like zipping. Here it is.
[PlaylistTemplates.zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/10552035/PlaylistTemplates.zip)

**Comment by greyshirtguy** [comment]
File looks fine to me -> checking with protoc I get no error to decode it and a clean output that makes sense:
`protoc ./playlistTemplate.proto --decode rv.data.PlaylistTemplate < /Users/dan/Desktop/PlaylistTemplates`

A little snip of first page of output:
![image](https://user-images.githubusercontent.com/1886513/215955197-b2297534-c52b-4181-9e64-fad0cdcf27fe.png)

**Comment by arlinsandbulte** [comment]
Sorry, I've been busy/distracted lately.  So I have not been very responsive here.
I've verified that your PlaylistTemplates file does produce the error with the old code.  
And Dan has verified it works with the updated protocol buf code.

So, I think this is all pretty straight-forward.  I just need to find some time to hammer the fix out.

**Comment by Brotuulaan** [comment]
Great! I'm glad it was simple to narrow down and can be addressed!

**Comment by arlinsandbulte** [comment]
I think I got this resolved.  Code is updated on GitHub.
But, I am having problems compiling a standalone app for MacOS (using pyinstaller).  
I can compile arm64 (e.g. Apple Silicon), but I can't get it to work yet for x86_64, which is what I have always done before
> x86_64 executables are compatible with both 'Intel Silicon' natively and 'Apple Silicon' with Rosetta.
> arm64 executables are will only run on Apple Silicon.
> universal2 executables can run on both Intel & Applie Silicon, but I could not get that to work yet either.

I would like to release this fix on Monday if I can get pyinstaller to give me a good x86_64 complied app.

In the meantime, if you wish, feel free to check out pre-releases of Pro7 Media Sweeper in the attached zip files.
And, if anyone can provide a compiled x86_64 app from the source code, let me know.
[Pro7 Media Sweeper (Mac-x86_64 v2.3.0).zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/10609391/Pro7.Media.Sweeper.Mac-x86_64.v2.3.0.zip) <- Successfully Compiles, but won't open on my M1 Mac Mini.
[Pro7 Media Sweeper (Mac-arm64 v2.3.0).zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/10609337/Pro7.Media.Sweeper.Mac-arm64.v2.3.0.zip)
[Pro7 Media Sweeper (Win v2.3.0).zip](https://github.com/arlinsandbulte/Pro7-Media-Sweeper/files/10609338/Pro7.Media.Sweeper.Win.v2.3.0.zip)

**Comment by arlinsandbulte** [comment]
Original issue is resolved.  Marking this issue as closed.
