### ISSUE TITLE
Application does not open V2.3.0 Mac x86-64

### ISSUE THREAD

**Issue by Cmillets** [arlinsandbulte/Pro7-Media-Sweeper#13]
Once downloaded and unzipped the application says it's open but does not display interface.

2018 Mac Mini i7

**Comment by arlinsandbulte** [comment]
I was a afraid of this...
I had some issues using pyinstaller to compile executables for Mac.
I only have an M1 Mac Mini, so I cannot test how the x86_64 executables work an Intel Mac platform.

I'll need to do more investigating on this, but in the meantime, if you or anyone else is successful compiling the script for Intel Mac, let me know.

**Comment by arlinsandbulte** [comment]
I don't have an intel Mac to test this on.
So, I've been compiling both arm64 & x86_64 release versions.
There has been no feedback regarding this application not working on x86_64.

So, I am going to close this issue out as completed, assuming the x86_64 executables are working with intel macs.
Feel free to re-open if there is an issue running the x86_64 executable on an intel mac.
Thanks.
