### ISSUE TITLE
Possible to assign the sweep folder?

### ISSUE THREAD

**Issue by stubish1** [arlinsandbulte/Pro7-Media-Sweeper#17]
I know this may be a big deal. but lets say you've got the library on a SSD and you want to sweep it to a HDD that's the 'stoarge' drive on the machine?

Could it be possible to assign the sweep folder to a custom location?

Hope that makes sense.

**Comment by arlinsandbulte** [comment]
I don't quite understand your question.
Do you want to change the folder to be swept?  This can be changed by the user now.
Or, do you want to change the folder where the swept files are moved to?  This cannot be changed now.  They are always moved to a folder in the user's home directory.  I could add this feature, but I don't see why.

**Comment by arlinsandbulte** [comment]
No feedback.  I'm closing this issue out.
